### ISSUE TITLE
Missing build system

### ISSUE THREAD

**Issue by xmatej** [bombadil/mod_proxy_msrpc#7]
Hi, 
I am trying to load module mod_proxy_msrpc into apache 2.4.4 on RHEL6. 

I am getting the error 

httpd: Syntax error on line 173 of /etc/httpd/conf/httpd.conf: Cannot load lib64/httpd/modules/mod_proxy_msrpc.so into server: /usr/lib64/httpd/modules/mod_proxy_msrpc.so: undefined symbol: msrpc_sync_wait

during config file syntax check

Is there any module depedency. Unfortunattelly I am not able to find any informations on google

**Comment by bombadil** [comment]
You need to build the binary module using _all_ the source files, and not just the mod_proxy_msrpc.c. Typically the following command is used to build the module

```
apxs -luuid -c mod_proxy_msrpc.c msrpc_pdu_parser.c msrpc_sync.c
```

I would like to have some autotools generated makefiles so that building the module becomes easier. If anybody is willing to work on that, I am definitely interested in integrating the needed changes.

**Comment by bombadil** [comment]
I've just added a tiny autoconf based build system (commit 0e8ebb9 and commit e826f0a).
